version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to docker hub...
      - $(docker login --username pmahalakshmi --password-stdin Mahala9*)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t simpleapi:latest .
      - docker tag simpleapi:latest pmahalakshmi/mylearning:v1  
  post_build:
    commands:
      - echo Build completed on `date`
      
