version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - $(aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y3l6p5i8)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t simpleapi:latest .
      - docker tag simpleapi:latest 012345678910.dkr.ecr.us-east-1.amazonaws.com/simple-api-codebuild:latest    
  post_build:
    commands:
      - echo Build completed on `date`
      
