version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t helloworld .
  build:
    commands:
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      
